#!/bin/bash

# Terraform Plan Script for Document Service Infrastructure
# This script shows what infrastructure would be created

echo "================================================="
echo "SoloPilot Document Service - Terraform Plan"
echo "================================================="
echo ""
echo "This script would create the following resources:"
echo ""
echo "1. S3 Bucket:"
echo "   - Name: solopilot-{env}-documents-{account-id}"
echo "   - Versioning: Enabled"
echo "   - Encryption: AES256"
echo "   - Public Access: Blocked"
echo "   - Lifecycle: Delete old versions after 30 days"
echo ""
echo "2. IAM Policy:"
echo "   - Name: solopilot-{env}-lambda-s3-access"
echo "   - Permissions: GetObject, PutObject, DeleteObject, ListBucket"
echo ""
echo "3. Helper Functions:"
echo "   - s3_helpers.js module for signed URL generation"
echo "   - Support for 24-hour download URLs"
echo "   - Structured key generation for documents"
echo ""
echo "================================================="
echo "To apply this infrastructure:"
echo ""
echo "1. Install Terraform:"
echo "   brew install terraform"
echo ""
echo "2. Initialize Terraform:"
echo "   cd doc-service/terraform"
echo "   terraform init"
echo ""
echo "3. Review the plan:"
echo "   terraform plan"
echo ""
echo "4. Apply (creates resources):"
echo "   terraform apply"
echo ""
echo "================================================="
echo "Estimated Monthly Cost: < $0.50"
echo "(S3 storage only, no data transfer costs included)"
echo "================================================="
