name: Serena LSP Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-serena:
    runs-on: ubuntu-latest
    
    services:
      serena:
        image: ghcr.io/rafaykhurram/solopilot-serena:latest
        ports:
          - 8765:8765
        options: >-
          --health-cmd "curl -f http://localhost:8765/health || exit 1"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
      
    - name: Create virtual environment
      run: |
        source $HOME/.local/bin/env
        uv venv .venv
        source .venv/bin/activate
        uv pip install -r requirements.txt
    
    - name: Install Serena
      run: |
        source $HOME/.local/bin/env
        uvx --from git+https://github.com/oraios/serena index-project .
    
    - name: Test Serena Integration
      env:
        CONTEXT_ENGINE: serena
        SERENA_SSE_URL: http://localhost:8765
      run: |
        source .venv/bin/activate
        python -m pytest tests/test_serena_context_engine.py -v --tb=short
        
    - name: Test Performance Benchmarks
      env:
        CONTEXT_ENGINE: serena
        SERENA_SSE_URL: http://localhost:8765
      run: |
        source .venv/bin/activate
        python tests/performance/serena_benchmark.py
        
    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: serena-benchmark-results
        path: tests/performance/serena_benchmark_results.json